references = []

[version]
channel = "Final"
major = 0
minor = 0
patch = 22
revision = 0

[settings]
git_url_prefix = ""

[[references]]
file_name = "package.json"
output_type = "String"
variable = "version"
