[settings]
git_url_prefix = "https://github.com/ginger-society/ginger-ui"
take_snapshots = false

[version]
channel = "Final"
major = 0
minor = 56
patch = 0
revision = 0

[[references]]
file_name = "package.json"
output_type = "String"
variable = "version"
